server:
  port: 8092

spring:
  application:
    name: client

eureka:
  client:
    serviceUrl:
      defaultZone: http://8.129.97.122:8090/eureka/
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    #status-page-url: http://${spring.cloud.client.ip-address:localhost}:${server.port}/swagger-ui.html
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）
